{{- if and .Values.image.credentials.username .Values.image.credentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-indexer-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.credentials.registry .Values.image.credentials.username .Values.image.credentials.password (printf "%s:%s" .Values.image.credentials.username .Values.image.credentials.password | b64enc) | b64enc }}
{{- end }}
