apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ontoserver-indexer.jobName" . }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: indexer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/run.sh"]
          args:
            - indexCodeSystemDebug
            - -s
            - {{ .Values.codeSystem.url | quote }}
            - -v
            - {{ .Values.codeSystem.version | quote }}
            {{- range .Values.rf2.files }}
            - -f
            - {{ . | quote }}
            {{- end }}
            - -k
            - {{ .Values.rf2.kind | lower | quote }}
            - -synd
            - {{ .Values.syndication.endpoint | quote }}
            - -feed
            - {{ .Values.syndication.feed | quote }}
            {{- if .Values.syndication.entryFileName }}
            - -file
            - {{ .Values.syndication.entryFileName | quote }}
            {{- end }}
            - -t
            - {{ .Values.syndication.entryTitle | quote }}
            {{- range .Values.syndication.securityLabels }}
            - -perms
            - {{ . | quote }}
            {{- end }}
          env:
            - name: JAVA_OPTS
              value: "-Xmx{{ .Values.resources.memoryGb }}g"
            {{- $oauth2SecretName := include "ontoserver-indexer.oauth2SecretName" . }}
            {{- if $oauth2SecretName }}
            - name: authentication.oauth.endpoint.0
              value: {{ .Values.syndication.endpoint | quote }}
            - name: authentication.oauth.endpoint.token_endpoint.0
              value: {{ .Values.syndication.tokenEndpoint | quote }}
            - name: authentication.oauth.endpoint.strategy.0
              value: body
            - name: authentication.oauth.endpoint.client_id.0
              valueFrom:
                secretKeyRef:
                  name: {{ $oauth2SecretName }}
                  key: clientId
            - name: authentication.oauth.endpoint.client_secret.0
              valueFrom:
                secretKeyRef:
                  name: {{ $oauth2SecretName }}
                  key: clientSecret
            {{- end }}
            {{- $basicSecretName := include "ontoserver-indexer.basicSecretName" . }}
            {{- if $basicSecretName }}
            - name: authentication.basic.endpoint.0
              value: {{ .Values.syndication.endpoint | quote }}
            - name: authentication.basic.endpoint.user.0
              valueFrom:
                secretKeyRef:
                  name: {{ $basicSecretName }}
                  key: username
            - name: authentication.basic.endpoint.password.0
              valueFrom:
                secretKeyRef:
                  name: {{ $basicSecretName }}
                  key: password
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.memoryGb }}G
            limits:
              memory: {{ .Values.resources.memoryGb }}G
