apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ontoserver-indexer.jobName" . }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: indexer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/run.sh"]
          args:
            - indexCodeSystemDebug
            - -s
            - {{ .Values.codeSystem.url | quote }}
            - -v
            - {{ .Values.codeSystem.version | quote }}
            {{- range .Values.rf2.files }}
            - -f
            - {{ . | quote }}
            {{- end }}
            - -k
            - {{ .Values.rf2.kind | lower | quote }}
            - -synd
            - {{ .Values.syndication.endpoint | quote }}
            - -feed
            - {{ .Values.syndication.feed | quote }}
            {{- if .Values.syndication.entryFileName }}
            - -file
            - {{ .Values.syndication.entryFileName | quote }}
            {{- end }}
            - -t
            - {{ .Values.syndication.entryTitle | quote }}
            {{- range .Values.syndication.securityLabels }}
            - -perms
            - {{ . | quote }}
            {{- end }}
          env:
            - name: JAVA_OPTS
              value: "-Xmx{{ .Values.resources.memoryGb }}g"
          resources:
            requests:
              memory: {{ .Values.resources.memoryGb }}G
            limits:
              memory: {{ .Values.resources.memoryGb }}G
