apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ontoserver-indexer.jobName" . }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: indexer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              memory: {{ .Values.resources.memoryGb }}G
            limits:
              memory: {{ .Values.resources.memoryGb }}G
