{{- if or .Values.auth.oauth2.clientId .Values.auth.basic.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ontoserver-indexer.secretName" . }}
type: Opaque
data:
  {{- if .Values.auth.oauth2.clientId }}
  clientId: {{ .Values.auth.oauth2.clientId | b64enc }}
  clientSecret: {{ .Values.auth.oauth2.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.auth.basic.username }}
  username: {{ .Values.auth.basic.username | b64enc }}
  password: {{ .Values.auth.basic.password | b64enc }}
  {{- end }}
{{- end }}
