{{- if and .Values.varnish.enabled .Values.varnish.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-varnish-metrics
  labels:
    {{- include "ontoserver-extras.labels" . | nindent 4 }}
    {{- include "ontoserver-extras.varnish.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ontoserver-extras.varnish.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      interval: {{ .Values.varnish.metrics.interval }}
      scrapeTimeout: {{ .Values.varnish.metrics.scrapeTimeout }}
      path: /metrics
      honorLabels: true
{{- end }}
