{{- if .Values.ontoserver.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-ontoserver-external-secret
spec:
  refreshInterval: {{ .Values.ontoserver.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ required "ontoserver.externalSecret.secretStoreRef.name is required when externalSecret is enabled" .Values.ontoserver.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.ontoserver.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-ontoserver-external-secrets
    creationPolicy: Owner
  {{- if .Values.ontoserver.externalSecret.data }}
  data:
    {{- toYaml .Values.ontoserver.externalSecret.data | nindent 4 }}
  {{- end }}
  {{- if .Values.ontoserver.externalSecret.dataFrom }}
  dataFrom:
    {{- toYaml .Values.ontoserver.externalSecret.dataFrom | nindent 4 }}
  {{- end }}
{{- end }}
