{{- if .Values.ontoserver.deployment.persistence.enabledForDeployment }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ontoserver-files
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.ontoserver.deployment.persistence.files.existingVolume.enabled }}
  volumeName: {{ .Values.ontoserver.deployment.persistence.files.existingVolume.name }}
  {{- end }}
  resources:
    requests:
      storage: "{{ required "ontoserver.resources.ontoserver.requests.storage is required" .Values.ontoserver.resources.ontoserver.requests.storage }}"
  {{- if .Values.ontoserver.deployment.persistence.files.storageClass.provided.enabled }}
  storageClassName: {{ .Release.Name }}-ontoserver-files
  {{- else if .Values.ontoserver.deployment.persistence.files.storageClass.name }}
  storageClassName: {{ .Values.ontoserver.deployment.persistence.files.storageClass.name }}
  {{- end }}
  accessModes:
    - "{{ .Values.ontoserver.deployment.persistence.files.accessMode }}"
{{- if and (eq .Values.ontoserver.deployment.persistence.mode "split") .Values.ontoserver.deployment.db.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ontoserver-db-files
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.ontoserver.deployment.persistence.dbfiles.existingVolume.enabled }}
  volumeName: {{ .Values.ontoserver.deployment.persistence.dbfiles.existingVolume.name }}
  {{- end }}
  resources:
    requests:
      storage: "{{ required "ontoserver.resources.db.requests.storage is required" .Values.ontoserver.resources.db.requests.storage }}"
  {{- if .Values.ontoserver.deployment.persistence.dbfiles.storageClass.provided.enabled }}
  storageClassName: {{ .Release.Name }}-ontoserver-db-files
  {{- else if .Values.ontoserver.deployment.persistence.dbfiles.storageClass.name }}
  storageClassName: {{ .Values.ontoserver.deployment.persistence.dbfiles.storageClass.name }}
  {{- end }}
  accessModes:
    - "{{ .Values.ontoserver.deployment.persistence.dbfiles.accessMode }}"
{{- end }}
{{- end }}