kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ontoserver-service
  labels:
    {{- include "ontoserver.labels" . | nindent 4 }}
    {{- include "ontoserver.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.ontoserver.deployment.containerPort }}
  selector:
    app: {{ .Release.Name }}-ontoserver
{{- if eq .Values.ontoserver.deployment.type "scaled" }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ontoserver-clustering-service
  labels:
    {{- include "ontoserver.labels" . | nindent 4 }}
    {{- include "ontoserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: clustering
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: cluster-bind
      port: 7800
    - name: multicast
      port: 46655
      protocol: UDP
  selector:
    app: {{ .Release.Name }}-ontoserver
{{- end }}
{{- if eq .Values.ontoserver.deployment.kind "StatefulSet" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ontoserver-headless
  labels:
    {{- include "ontoserver.labels" . | nindent 4 }}
    {{- include "ontoserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-ontoserver
{{- end }}
{{- if and (eq .Values.ontoserver.deployment.kind "StatefulSet") (eq .Values.ontoserver.deployment.type "scaled") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ontoserver-pod0-service
  labels:
    {{- include "ontoserver.labels" . | nindent 4 }}
    {{- include "ontoserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: closure
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.ontoserver.deployment.containerPort }}
  selector:
    app: {{ .Release.Name }}-ontoserver
    statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-statefulset-0
{{- end }}