{{- if .Values.ontoserver.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ontoserver.serviceAccount.name | default (printf "%s-ontoserver" .Release.Name) }}
  labels:
    {{- include "ontoserver.labels" . | nindent 4 }}
  {{- if gt (len .Values.ontoserver.serviceAccount.annotations) 0 }}
  annotations:
    {{- toYaml .Values.ontoserver.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
